# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: AuraOS
description: AuraOS

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 41

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - micro
      - fastfetch
      - htop
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.videolan.VLC
          - org.kde.kcalc
          - org.kde.okular
          - org.kde.ark
